spring.application.name=login-page-backend
spring.profiles.active=dev
api.security.token.secret=${JWT_SECRET}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
